var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://"),na,r,t,oa,pa,v,w,x,y;
function qa(){var a=na.buffer;r=new Int8Array(a);oa=new Int16Array(a);t=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function ra(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&"function"==typeof WebAssembly.instantiateStreaming&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(h)},ya=[],za=[],Aa=()=>{var a=h.preRun.shift();za.push(a)},Ba=!0,Ca=0,B={},Da=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Ea=a=>{ma=a;Ba||0<Ca||(h.onExit?.(a),p=!0);fa(a,new wa(a))},Fa=a=>{ma=a;Ea(a)},Ga=()=>{if(!(Ba||0<Ca))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ha=a=>{if(!p)try{a(),Ga()}catch(b){Da(b)}},Oa=(a,b)=>{Ia=a;Ja=b;if(D)if(Ka||=!0,0==a)E=function(){setTimeout(F,Math.max(0,La+b-performance.now())|0)};else if(1==a)E=function(){Ma(F)};else if(2==a){if("undefined"==
typeof Na)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Na=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Na=setImmediate;E=function(){Na(F)}}},Xa=(a,b,c,d,e)=>{function g(){return f<Pa?(Ga(),!1):!0}D=a;Qa=d;var f=Pa;Ka=!1;F=function(){if(!p)if(0<Ra.length){var l=
Ra.shift();l.zd(l.od);if(Sa){var n=Sa,q=0==n%1?n-1:Math.floor(n);Sa=l.qd?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Sa??0,q=Ta.vd??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(F,0)}else if(g())if(Ua=Ua+1|0,1==Ia&&1<Ja&&0!=Ua%Ja)E();else{0==Ia&&(La=performance.now());a:if(!p){for(l of Va)if(!1===l())break a;Ha(a);for(n of Wa)n()}g()&&E()}};e||(0<b?Oa(0,1E3/b):Oa(1,1),E());if(c)throw"unwind";},Ka=!1,E=
null,Pa=0,D=null,Qa=0,Ia=0,Ja=0,Ua=0,Ra=[],Va=[],Wa=[];function Ya(){E=null;Pa++}var Za=0;function Ma(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Za)Za=b+1E3/60;else for(;b+2>=Za;)Za+=1E3/60;setTimeout(a,Math.max(Za-b,0))}}
var Ta={},La,F,Na,Sa,$a="undefined"!=typeof TextDecoder?new TextDecoder:void 0,G=(a=0,b)=>{var c=t;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&$a)return $a.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|g);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
ab=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?G(a):"":a;return ab[a]||("undefined"!=typeof document?document.querySelector(a):null)},bb=a=>0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},cb=[],db,I=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};function eb(a){var b=J.rc[a];b.target.removeEventListener(b.qc,b.Tc,b.sc);J.rc.splice(a,1)}
function fb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Gc&&J.jd.Ec){var a=J.wc;J.wc=[];for(var b of a)b.Jc(...b.Pc)}}function K(a){if(!a.target)return-4;if(a.tc)a.Tc=function(c){++J.Gc;J.jd=a;fb();a.uc(c);fb();--J.Gc},a.target.addEventListener(a.qc,a.Tc,a.sc),J.rc.push(a);else for(var b=0;b<J.rc.length;++b)J.rc[b].target==a.target&&J.rc[b].qc==a.qc&&eb(b--);return 0}function gb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={pd:0,Ad:0,Hc:0,Dc:0,Nc:0,Lc:0,Fc:0,td:0,Fd:0,sd:0,yd:0,Ic:0,Nd:0,Kc:0,Cd(a,b,c){r.set(r.subarray(b,b+c),a)},Hd(){for(;J.rc.length;)eb(J.rc.length-1);J.wc=[]},Gc:0,wc:[],rd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of J.wc)if(e.Jc==a&&d(e.Pc,c))return;J.wc.push({Jc:a,Yc:b,Pc:c});J.wc.sort((g,f)=>g.Yc<f.Yc)},Jd(a){J.wc=J.wc.filter(b=>b.Jc!=a)},rc:[],Id:(a,b)=>{for(var c=0;c<J.rc.length;++c)J.rc[c].target!=a||b&&b!=J.rc[c].qc||
eb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-
e},hb=(a,b,c,d,e,g)=>{J.Fc||(J.Fc=M(256));a={target:H(a),qc:g,tc:d,uc:(f=event)=>{var l=f.target.id?f.target.id:"",n=J.Fc;L(gb(f.target),n+0,128);L(l,n+128,128);I(d)(e,n,b)&&f.preventDefault()},sc:c};return K(a)},ib=(a,b,c,d,e,g)=>{J.Hc||(J.Hc=M(160));a={target:H(a),qc:g,tc:d,uc:f=>{var l=J.Hc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlkey;r[l+13]=f.shiftkey;r[l+14]=f.altkey;r[l+15]=f.metakey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;L(f.key||"",l+32,32);
L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},sc:c};return K(a)},jb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlkey;r[a+25]=b.shiftkey;r[a+26]=b.altkey;r[a+27]=b.metakey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=bb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},kb=(a,b,c,d,e,g)=>{J.Dc||(J.Dc=M(64));a=H(a);return K({target:a,
Ec:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,qc:g,tc:d,uc:(f=event)=>{jb(J.Dc,f,a);I(d)(e,J.Dc,b)&&f.preventDefault()},sc:c})},lb=(a,b,c,d)=>{J.Ic||(J.Ic=M(257));return K({target:a,qc:"pointerlockchange",tc:d,uc:(e=event)=>{var g=J.Ic,f=document.pointerLockElement;r[g]=!!f;var l=f?.id||"";L(gb(f),g+1,128);L(l,g+129,128);I(d)(20,g,b)&&e.preventDefault()},sc:c})},mb=(a,b,c,d)=>K({target:a,qc:"pointerlockerror",tc:d,uc:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},sc:c}),nb=(a,b,c,d)=>{J.Lc||
(J.Lc=M(36));a=H(a);return K({target:a,qc:"resize",tc:d,uc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=J.Lc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},sc:c})},ob=(a,b,c,d,e,g)=>{J.Kc||(J.Kc=M(1552));a=H(a);return K({target:a,Ec:"touchstart"==g||"touchend"==g,qc:g,tc:d,uc:f=>{var l={},n=f.touches;
for(var q of n)q.Uc=q.Wc=0,l[q.identifier]=q;for(var u of f.changedTouches)u.Uc=1,l[u.identifier]=u;for(var N of f.targetTouches)l[N.identifier].Wc=1;n=J.Kc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlkey;r[n+13]=f.shiftkey;r[n+14]=f.altkey;r[n+15]=f.metakey;q=n+16;u=bb(a);N=0;for(let C of Object.values(l))if(l=q>>2,v[l]=C.identifier,v[l+1]=C.screenX,v[l+2]=C.screenY,v[l+3]=C.clientX,v[l+4]=C.clientY,v[l+5]=C.pageX,v[l+6]=C.pageY,r[q+28]=C.Uc,r[q+29]=C.Wc,v[l+8]=C.clientX-(u.left|0),v[l+9]=C.clientY-(u.top|
0),q+=48,31<++N)break;v[n+8>>2]=N;I(d)(e,n,b)&&f.preventDefault()},sc:c})},O,pb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},qb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},tb=1,ub=[],P=[],vb=[],wb=[],Q=[],R=[],xb=[],yb=[],S=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Cb(d);g?(g.name=f,d[f]=g):T||=1282;v[b+4*e>>2]=f}},Eb=(a,b)=>{a.Xc||(a.Xc=a.getContext,a.getContext=function(d,e){e=a.Xc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Vc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.Vc,Oc:a};a.canvas&&(a.canvas.nd=d);yb[c]=d;("undefined"==typeof b.Sc||b.Sc)&&Fb(d);return c},Fb=a=>{a||=V;if(!a.md){a.md=!0;var b=a.Oc;b.Ed=b.getExtension("WEBGL_multi_draw");b.xd=b.getExtension("EXT_polygon_offset_clamp");b.wd=b.getExtension("EXT_clip_control");b.Od=b.getExtension("WEBGL_polygon_mode");pb(b);qb(b);rb(b);b.ud=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Bd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Rc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Rc)b.Rc=b.getExtension("EXT_disjoint_timer_query");sb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Gb=(a,b,c,d,e,g)=>{a={target:H(a),qc:g,tc:d,uc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},sc:c};K(a)},Hb=(a,b,c,d)=>{J.Nc||(J.Nc=M(96));return K({target:a,Ec:!0,qc:"wheel",tc:d,uc:(e=event)=>{var g=J.Nc;jb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;I(d)(9,g,b)&&e.preventDefault()},sc:c})},Ib=["default","low-power","high-performance"],Jb=[],Kb=()=>{var a=sb(O);return a=a.concat(a.map(b=>"GL_"+b))},Lb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Kb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Nb=a=>{var b=Mb(a)+1,c=M(b);c&&L(a,c,
b);return c},Ob=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Pb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:pa},W=a=>{var b=O.kd;if(b){var c=b.zc[a];"number"==typeof c&&(b.zc[a]=c=O.getUniformLocation(b,b.gd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Qb=[],Sb=a=>{var b=Mb(a)+1,c=Rb(b);L(a,c,b);return c},Vb=a=>{var b=Tb();a();Ub(b)};h.requestAnimationFrame=Ma;h.pauseMainLoop=Ya;
h.resumeMainLoop=function(){Pa++;var a=Ia,b=Ja,c=D;D=null;Xa(c,0,!1,Qa,!0);Oa(a,b);E()};h.preMainLoop&&Va.push(h.preMainLoop);h.postMainLoop&&Wa.push(h.postMainLoop);for(let a=0;32>a;++a)Jb.push(Array(a));for(var Wb=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Wb.subarray(0,Y);var Xb=new Int32Array(288);for(Y=0;288>=Y;++Y)Qb[Y]=Xb.subarray(0,Y);h.noExitRuntime&&(Ba=h.noExitRuntime);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);
var M,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,Ub,Rb,Tb,mc={jb:()=>ra(""),fb:()=>{Ba=!1;Ca=0},gb:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ha(()=>lc(a,performance.now()))},b);B[a]={id:c,Md:b};return 0},Ta:()=>{Ya();D=null},ga:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ia:(a,b,c)=>{a=H(a);if(!a)return-4;a=bb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},z:()=>performance.now(),Ua:()=>performance.now(),_a:(a,b)=>{function c(d){I(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);qa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},Q:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),fa:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),_:(a,
b,c,d)=>ib(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>ib(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>ib(a,b,c,d,3,"keyup"),$a:(a,b,c)=>{a=I(a);Xa(a,b,c)},ea:(a,b,c,d)=>kb(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>kb(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>kb(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>kb(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>kb(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?lb(a,b,c,d):-4:-1,S:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?mb(a,b,c,d):-4:-1,ha:(a,b,c,d)=>nb(a,
b,c,d),U:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Hb(a,b,c,d):-1:-4,Za:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+
5],powerPreference:Ib[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Vc:v[c+4],Dd:v[c+5],Sc:r[b+24],ld:r[b+25],Gd:v[c+7],Kd:r[b+32]};a=H(a);return!a||b.ld?0:Eb(a,b)},Ya:a=>{V=yb[a];h.ctx=O=V?.Oc;return!a||O?0:-5},p:a=>O.activeTexture(a),A:(a,b)=>{O.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?O.Qc=b:35052==a&&(O.yc=b);O.bindBuffer(a,ub[b])},a:(a,b,c)=>{O.bindBufferBase(a,b,ub[c])},j:(a,b)=>{O.bindFramebuffer(a,vb[b])},Fa:(a,b)=>{O.bindRenderbuffer(a,wb[b])},o:(a,b)=>{O.bindSampler(a,S[b])},d:(a,b)=>
{O.bindTexture(a,Q[b])},N:a=>{O.bindVertexArray(xb[a])},J:(a,b,c,d)=>O.blendColor(a,b,c,d),K:(a,b)=>O.blendEquationSeparate(a,b),L:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),lb:(a,b,c,d,e,g,f,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,g,f,l,n,q),Ha:(a,b,c,d)=>{2<=V.version?c&&b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},D:(a,b,c,d)=>{2<=V.version?c&&O.bufferSubData(a,b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},ra:a=>O.checkFramebufferStatus(a),Gb:(a,b,c,d)=>O.clearBufferfi(a,
b,c,d),oa:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Fb:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},q:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Jb:a=>{O.compileShader(R[a])},Aa:(a,b,c,d,e,g,f,l,n)=>{2<=V.version?O.yc||!l?O.compressedTexSubImage2D(a,b,c,d,e,g,f,l,n):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t,n,l):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t.subarray(n,n+l))},za:(a,b,c,d,e,g,f,l,n,q,u)=>{O.yc?O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,q,u):O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,t,u,q)},Pb:()=>
{var a=Cb(P),b=O.createProgram();b.name=a;b.Cc=b.Ac=b.Bc=0;b.Mc=1;P[a]=b;return a},Mb:a=>{var b=Cb(R);R[b]=O.createShader(a);return b},G:a=>O.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=ub[d];e&&(O.deleteBuffer(e),e.name=0,ub[d]=null,d==O.Qc&&(O.Qc=0),d==O.yc&&(O.yc=0))}},g:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=vb[d];e&&(O.deleteFramebuffer(e),e.name=0,vb[d]=null)}},l:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=wb[d];e&&(O.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},n:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(O.deleteSampler(e),e.name=0,S[d]=null)}},r:a=>{if(a){var b=R[a];b?(O.deleteShader(b),R[a]=null):T||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(O.deleteTexture(e),e.name=0,Q[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];O.deleteVertexArray(xb[d]);xb[d]=null}},w:a=>O.depthFunc(a),v:a=>{O.depthMask(!!a)},e:a=>O.disable(a),M:a=>{O.disableVertexAttribArray(a)},
nb:(a,b,c)=>{O.drawArrays(a,b,c)},ob:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=Jb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},pb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},qb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},i:a=>O.enable(a),Ab:a=>{O.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,wb[d])},m:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,Q[d],e)},y:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,Q[c],d,e)},H:a=>O.frontFace(a),Ia:(a,b)=>{U(a,
b,"createBuffer",ub)},ta:(a,b)=>{U(a,b,"createFramebuffer",vb)},Ga:(a,b)=>{U(a,b,"createRenderbuffer",wb)},ya:(a,b)=>{U(a,b,"createSampler",S)},Da:(a,b)=>{U(a,b,"createTexture",Q)},Sa:(a,b)=>{U(a,b,"createVertexArray",xb)},Hb:(a,b)=>O.getAttribLocation(P[a],b?G(b):""),c:(a,b)=>Lb(a,b),Ob:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=tb)T||=1281;else if(a=P[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
v[c>>2]=a.length+1;else if(35719==b){if(!a.Cc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Cc=Math.max(a.Cc,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Cc}else if(35722==b){if(!a.Ac)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Ac=Math.max(a.Ac,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Ac}else if(35381==b){if(!a.Bc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Bc=Math.max(a.Bc,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Bc}else v[c>>2]=O.getProgramParameter(a,
b);else T||=1281},Ib:(a,b,c,d)=>{a=O.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(R[a],b):T||=1281},Qa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=zb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Kb().map(Nb),c=zb[a]=c,0>b||
b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},va:(a,b)=>{b=b?G(b):"";if(a=P[a]){var c=a,d=c.zc,e=c.hd,g;if(!d){c.zc=d={};c.gd={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,g);var n=l.name;l=l.size;var q=Ob(n);q=0<q?n.slice(0,q):n;var u=c.Mc;c.Mc+=l;e[q]=[l,u];for(n=0;n<l;++n)d[u]=n,c.gd[u++]=q}}c=a.zc;d=0;e=b;g=Ob(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.hd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else T||=
1281;return-1},kb:(a,b,c)=>{for(var d=Jb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,d)},xa:a=>{a=P[a];O.linkProgram(a);a.zc=0;a.hd={}},Ra:(a,b)=>{3317==a?Ab=b:3314==a&&(Bb=b);O.pixelStorei(a,b)},I:(a,b)=>O.polygonOffset(a,b),mb:a=>O.readBuffer(a),Ea:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),B:(a,b,c)=>{O.samplerParameterf(S[a],b,c)},h:(a,b,c)=>{O.samplerParameteri(S[a],b,c)},pa:(a,b,c,d)=>O.scissor(a,b,c,d),Lb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?
G(f,d?w[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(R[a],e)},Oa:(a,b,c)=>O.stencilFunc(a,b,c),na:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),s:a=>O.stencilMask(a),Na:(a,b,c)=>O.stencilOp(a,b,c),ma:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Ca:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),f:(a,b,c,d,e,g,f,l,n)=>{if(2<=V.version){if(O.yc){O.texSubImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var q=Pb(l);O.texSubImage2D(a,b,c,d,e,g,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));
return}}if(n){q=Pb(l);var u=g*((Bb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Ab-1&-Ab);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,g,f,l,n)},C:(a,b,c,d,e,g,f,l,n,q,u)=>{if(O.yc)O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,u);else if(u){var N=Pb(q);O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,N,u>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,g,f,l,n,
q,null)},zb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(W(a),d)}},Nb:(a,b)=>{O.uniform1i(W(a),b)},vb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Qb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(W(a),d)}},yb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=
2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&O.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Qb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2iv(W(a),d)}},xb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,
c+12*b>>2);O.uniform3fv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Qb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(W(a),d)}},wb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(W(a),
d)}},sb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Qb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(W(a),d)}},rb:(a,b,c,d)=>{if(2<=V.version)b&&O.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+
6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=P[a];O.useProgram(a);O.kd=a},Bb:(a,b)=>{O.vertexAttribDivisor(a,b)},Db:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Eb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,e,g)},t:(a,b,c,d)=>O.viewport(a,b,c,d),eb:Ea,Sb:function(){h.Zc=a=>{0!=Zb()&&(a.preventDefault(),a.returnValue=" ")};
window.addEventListener("beforeunload",h.Zc)},ab:function(){h.ed=a=>{const b=a.clipboardData.getData("text");Vb(()=>{const c=Sb(b);Yb(c)})};window.addEventListener("paste",h.ed)},Wa:function(){h.Ld=[];h.$c=b=>{b.stopPropagation();b.preventDefault()};h.ad=b=>{b.stopPropagation();b.preventDefault()};h.bd=b=>{b.stopPropagation();b.preventDefault()};h.cd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.dd=c;$b(c.length);for(let e=0;e<c.length;e++)Vb(()=>{const g=Sb(c[e].name);
ac(e,g)});let d=0;b.shiftkey&&(d|=1);b.ctrlkey&&(d|=2);b.altkey&&(d|=4);b.metakey&&(d|=8);bc(b.clientX,b.clientY,d)};const a=h.xc;a.addEventListener("dragenter",h.$c,!1);a.addEventListener("dragleave",h.ad,!1);a.addEventListener("dragover",h.bd,!1);a.addEventListener("drop",h.cd,!1)},Qb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Va:function(a){const b=h.dd;return 0>a||a>=b.length?0:b[a].size},Pa:function(a,b,c,d,e){const g=new FileReader;g.onload=
f=>{f=f.target.result;f.byteLength>d?cc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),cc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{cc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.dd[a])},Ka:function(a,b){0!==b&&(document.title=b?G(b):"");a=a?G(a):"";void 0!==h.canvas&&("object"===typeof h.canvas?ab[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.xc=H(a);h.xc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.xc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Rb:function(){window.removeEventListener("beforeunload",h.Zc)},Xa:function(){window.removeEventListener("paste",h.ed)},Ma:function(){const a=h.xc;a.removeEventListener("dragenter",h.$c);a.removeEventListener("dragleave",h.ad);a.removeEventListener("dragover",h.bd);a.removeEventListener("drop",h.cd)},u:function(){h.xc&&h.xc.requestPointerLock&&h.xc.requestPointerLock()},Kb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,
b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},bb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Vb(()=>{const e=Sb(c),g=Sb(d);fc(e,g)})}},db:function(){return h.vc?h.vc.bufferSize:0},Cb:function(a,b,c){h.pc=null;h.vc=null;"undefined"!==typeof AudioContext?h.pc=
new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.pc=null,console.log("sokol_audio.h: no WebAudio support"));return h.pc?(console.log("sokol_audio.h: sample rate ",h.pc.sampleRate),h.vc=h.pc.createScriptProcessor(c,0,b),h.vc.onaudioprocess=d=>{const e=d.outputBuffer.length,g=ec(e);if(g){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let q=0;q<e;q++)n[q]=x[(g>>2)+(f*q+l)]}}},h.vc.connect(h.pc.destination),a=()=>{h.pc&&"suspended"===
h.pc.state&&h.pc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},hb:function(){return h.pc?h.pc.sampleRate:0},la:function(){const a=h.pc;null!==a&&(h.vc&&h.vc.disconnect(),a.close(),h.pc=null,h.vc=null)},cb:function(){if(h.pc)return"suspended"===h.pc.state?1:0},x:function(a,b,c,d,e,g){const f=b?G(b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);console.log(f,b);fetch(f,{method:"GET",headers:b}).then(l=>
{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=g?(t.set(n,e),hc(a,d,n.length)):jc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);kc(a)}):ic(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);kc(a)})},ka:function(a,b){const c=b?G(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),kc(a)):gc(a,Number(d))):ic(a,d.status)}).catch(d=>
{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);kc(a)})},ja:function(a,b){b=b?G(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Tb;qa();db=Z.lc;c=Z;h._fs_emsc_alloc=c.Vb;M=c.Wb;h._fs_emsc_load_snapshot_callback=c.Xb;h.__sapp_emsc_onpaste=Yb=c.Yb;h.__sapp_html5_get_ask_leave_site=Zb=c.Zb;h.__sapp_emsc_begin_drop=$b=c._b;h.__sapp_emsc_drop=ac=c.$b;h.__sapp_emsc_end_drop=bc=c.ac;h.__sapp_emsc_invoke_fetch_cb=cc=c.bc;h._main=dc=c.cc;h.__saudio_emsc_pull=ec=c.dc;h.__sargs_add_kvp=fc=c.ec;h.__sfetch_emsc_head_response=gc=c.fc;h.__sfetch_emsc_get_response=hc=c.gc;h.__sfetch_emsc_failed_http_status=
ic=c.hc;h.__sfetch_emsc_failed_buffer_too_small=jc=c.ic;h.__sfetch_emsc_failed_other=kc=c.jc;lc=c.kc;Ub=c.mc;Rb=c.nc;Tb=c.oc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:mc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=h.locateFile?h.locateFile("vic20.wasm",ia):ia+"vic20.wasm";return a((await va(b)).instance)})();
function nc(a=[]){var b=dc;a.unshift(ea);var c=a.length,d=Rb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Sb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Fa(g)}catch(f){Da(f)}}
function oc(a=da){function b(){h.calledRun=!0;if(!p){Z.Ub();h.onRuntimeInitialized?.();h.noInitialRun||nc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ya.push(c)}xa(ya)}}if(0<z)A=oc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();xa(za);0<z?A=oc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();oc();
