10 REM C64 BASIC CONTROL CODES DEMO
20 PRINT CHR$(147): PRINT : PRINT : PRINT
30 PRINT "CONTROL CODES DEMO"
40 PRINT "-------------------"
70 PRINT "{HOME}";"HOME","SCREEN CONTROLS:"
80 PRINT "{DOWN}";"DOWN";"  {UP}";"UP      ";:PRINT
90 PRINT "{LEFT}";" LEFT";"  {RIGHT}";"RIGHT";:PRINT
100 PRINT "{DEL}";" DEL   {INS}";"INS";:PRINT
110 PRINT
140 PRINT "COLORS:" : PRINT
150 PRINT " {BLACK}BLACK{RED}RED{CYAN}CYAN"
160 PRINT " {PURPLE}PURPLE{GREEN}GREEN{BLUE}BLUE{YELLOW}YELLOW"
230 PRINT: PRINT "PRESS ANY KEY...";
240 LOOP: 
245 GET A$
250 IF A$="" THEN GOTO LOOP
260 PRINT "{CLR}";"DONE" 