REM INIT M(7) FOR MAZE, W(3) FOR WALLS, 
REM SET COLORS CLEAR KEYB (198)
REM MQ=MODULO RESULT TEMP, QT=QUOTIENT TEMP
REM MAZE() ARRAY FOR MAZE DATA (MAX 100 CELLS = 6*10-1)
DIM M(7),W(3),MAZE(100) : POKE 53280,0 : POKE 53281,0 : POKE 198,0
?"{CLEAR}{WHITE}{SPACE*5}MAZE{DOWN}"
?"[L] LEFT" : ?"[R] RIGHT" : ?"[F] FWD" : ?"[M] MAP"
? : GOSUB WAITKEY

REM SEED RAND 
ZZ=RND(-TI) : ?"{CLEAR}GENERATING MAP..." : GOTO MAZEGEN

DRAWWALL: 
REM WALL DRAWING
REM CHECK IF NEED CONNECTING WALLS 
REM (TC=TOP CORNER, BC=B-CORNER, U/V=DIR VECTORS, LL=LINE LENGTH 40)
Y=PEEK(TC-U) : Z=PEEK(TC-U+LL) : IF ABS(U)=1 OR DC=0 THEN GOTO DRAWWALLSEG

REM IF ADJACENT EMPTY (32=SPACE), DRAW CONNECTING	
IF Y<>32 THEN IF Z<>32 THEN GOTO DRAWWALLSEG
I1=TC-U+LL: I2=BC-V-LL
FOR A=I1 TO I2 STEP LL : POKEA,W3 : NEXT

DRAWWALLSEG: 
REM DRAW TOP AND BOTTOM WALL SEGMENTS
POKE TC,TW : POKE BC,BW 
REM DRAW WALL SEGMENTS FOR DEPTH DW (DRAW WIDTH)
B=B+1 : IF B<DW THEN TC=TC+U : BC=BC+V : GOTO DRAWWALLSEG

REM IF MOVING HORIZ, DRAW CORNER PIECES
IF ABS(U)=1 THEN POKE TC,T1 : POKE BC,B1 

REM IF CORNERS MEET, WE ARE DONE
IF TC=BC-LL THEN RETURN

REM FILL IN SIDE WALLS
FOR B=TC+LL TO BC-LL STEP LL : POKE B,SW : NEXT : RETURN

GENWALLS: 
REM MAZE GEN FOR LEFT WALL (ML=LEFT DIR), 
REM U/V ARE DIR VECTORS, T1/B1/SW ARE WALL CHAR
F=ML : U=LL+1 : V=1-LL : T1=80 : B1=122 : SW=103

REM LOOP LEFT (X=4) AND RIGHT (X=6) WALLS
FOR X=4 TO 6 STEP 2 : TW=77 : BW=78 : B=0 : IF X=4 THEN GOTO GETDIR

REM RIGHT WALL (MR=RIGHT DIR) WITH DIFFERENT VECTORS
F=MR : U=LL-1 : V=-LL-1 : SW=101 : T1=79 : B1=76 : TW=78 : BW=77

REM GET DIR (LM) AND WALL DIVISOR (LD) FOR DIR
GETDIR: 
LM=M(F) : LD=W(F)

REM SKIP IF WE ARE AT EXIT
IF F=3 THEN IF OP=EC THEN UPDATEBOUNDS

REM ENSURE WALL DIVISOR IS AT LEAST 2
IF LD=0 THEN LD=2

REM CHECK IF CELL VALUE IS / BY WALL DIVISOR (OPEN), 
REM IF SO DRAW WALL BETWEEN BOUNDS M(X) AND M(X+1)
QV=Q : DV=LD : GOSUB FASTMOD
IF MQ=0 THEN TC=M(X) : BC=M(X+1) : GOSUB DRAWWALL : GOTO RESTOREVEC

REM OTHERWISE TRY PERPENDICULAR (CROSSING), ADJUST DIR
TW=99 : BW=100 : U=U-LL : V=V+LL : N=MAZE(OP+LM)

REM IF NEIGHBOR CELL IS DIV BY D, DRAW CROSSING WALL
QV=N : DV=D : GOSUB FASTMOD
IF MQ=0 THEN TC=M(X)+DW*LL : BC=M(X+1)+DW*-LL : GOSUB DRAWWALL

REM RESTORE DIR IF WE WERE MOVING HORIZ
RESTOREVEC: 
IF ABS(U)=1 THEN U=U+LL : V=V-LL

UPDATEBOUNDS: 
REM UPDATE WALL BOUNDARIES BASED ON DIR
M(X)=M(X)+DW*U : M(X+1)=M(X+1)+DW*V : NEXT

REM IF FACING EXIT, STOP GEN
IF M=3 THEN IF OP=EC THEN RETURN

REM CHECK IF CELL IS A WALL (NOT DIV BY D)
QV=Q : DV=D : GOSUB FASTMOD
IF MQ=0 THEN GOTO SCANLEFT

REM MOVE TO NEXT IN DIR, INC DEPTH COUNTER
OP=OP+M(M) : Q=MAZE(OP) : DC=DC+1 : IF DC<CD THEN GOTO GENWALLS

REM IF MAX DEPTH, RETURN
IF DC=CD THEN RETURN

REM FIND LEFT WALL BOUNDS BY SCANNING LEFT FOR SPACE
SCANLEFT: 
R=PEEK(M(4)-1)

REM IF SPACE, MOVE LEFT BOUND LEFT, REPEAT UNTIL EDGE
IF R=32 THEN M(4)=M(4)-1 : M(5)=M(5)-1 : IF M(4)<>TL+DW*LL THEN GOTO SCANLEFT

SCANRIGHT: 
REM FIND RIGHT WALL BY SCANNING RIGHT
R=PEEK(M(6)+1)

REM IF SPACE FOUND, MOVE BOUND RIGHT, REPEAT UNTIL EDGE
IF R=32 THEN M(6)=M(6)+1 : M(7)=M(7)+1 : IF M(6)<>TR+DW*LL THEN SCANRIGHT

REM DRAW TOP SEG BETWEEN L + R BOUNDS
FOR TC=M(4)TOM(6) : POKETC,W1 : NEXT

REM DRAW BOTTOM SEGS BETWEEN L+R BOUNDS
FOR BC=M(5)TOM(7) : POKEBC,W2 : NEXT : RETURN

LOOP: 
REM MAIN GAME LOOP
?"{HOME}AIR:";OX;"{LEFT}L"

GETINPUT: 
A$="" : POKE198,0 : WAIT198,1 : GETA$ : IF A$="" THEN GOTO GETINPUT

REM CALC POS IF MOVING FWD (F KEY), P=POSITION, 
REM M(M)=MOVE VECTOR FOR DIR
NP=P : Q=MAZE(P) : IF A$="F" THEN NP=P+M(M)

REM IF NOT MOVING, HANDLE ROTATION OR MAP DISPLAY
IF NP=P THEN GOTO ROTATE

REM CHECK IF REACHED EXIT - IF SO, PLAYER WINS!
IF NP=EC THEN ?"EXIT!"; : GOSUB WAITKEY : RUN

REM CHECK IF PATH IS OPEN 
REM IF OPEN MOVE TO NEW POSITION
QV=Q : DV=D : GOSUB FASTMOD
IF MQ><0 THEN P=NP : ?"FWD" : GOTO UPDIRS

REM WALL COLLISION - CANT MOVE FORWARD
?"OUCH! HIT WALL" : GOTO DECOX

ROTATE: 
REM ROTATION R=RIGHT TURN, L=LEFT TURN, M=SHOW MAP
NM=M : IF A$="R" THEN ?"R" : NM=M+1
IF A$="M" THEN GOSUB SHOWMAP
IF A$="L" THEN ?"L" : NM=M+3
IF NM=M THEN GOTO LOOP

REM WRAP DIR AROUND (0-3 NORTH, EAST, SOUTH, WEST)
IF NM>3 THEN NM=NM-4*INT(NM/4)
M=NM

UPDIRS:
REM UPDATE DIR
D=W(M) : Q=MAZE(P) : OP=P : ML=M-1 : MR=M+1

REM WRAP LEFT 
IF ML<0 THEN ML=3

REM WRAP RIGHT 
IF MR>3 THEN MR=0

DECOX: 
REM DEC O2, CHECK IF OUT OF AIR
OX=OX-OL : IF OX<0 THEN ?"OUT OF AIR!"; : GOSUB WAITKEY : RUN

REM INC TURN, SET FLAG
T=T+1 : TT=1

REM IF FLAG, GEN MAZE SECTION 
IF TT=1 THEN DC=0 : ? CHR$(147) : GOSUB GENWALLS

REM RESET WALL BOUNDS AND LOOP 
M(4)=TL : M(5)=BL : M(6)=TR : M(7)=BR : GOTO LOOP

MAZEINIT: 
REM FIND VALID STARTING POS
REM MOVE TO NEXT POS, WRAP AROUND IF PAST END
P=P+1 : IF P>EM THEN P=SM

PICKDIR: 
REM PICK RANDOM DIR (0-3)
A=INT(RND(1)*4) : DC=0

TRYDIR: 
REM TRY EACH DIR IN SEQUENCE
A=A+1 : DC=DC+1 : IF DC>3 THEN GOTO MAZEINIT

REM WRAP DIR
IF A>3 THEN A=0

REM CALC TARGET POS, CHECK IF WITHIN BOUNDS
M=P+M(A) : IF M<SM OR M>EM THEN GOTO TRYDIR

REM GET CURRENT AND TARGET CELL VALUES, IF
REM CELL IS UNINITD (210), MOVE THERE
CP=MAZE(P) : CM=MAZE(M)
IF C>0 AND CP=210 THEN P=M : GOTO PICKDIR

REM CHECK IF CELLS SAME VALUE OR UNINITD
TM=M
IF (CP=CM OR CM<210) AND C>0 THEN GOTO TRYDIR

REM CHECK EDGES
REM CANT MOVE RIGHT ON LEFT EDGE, LEFT ON RIGHT EDGE
ME=TM-L*INT(TM/L)
IF (ME=0 AND M(A)=1)OR(ME=G AND M(A)=-1) THEN GOTO TRYDIR

REM MERGE CELLS 
REM DIVIDE CELL VALUES BY WALL DIVISORS TO CREATE PASSAGES
REM OD=OTHER DIR DIVISOR, CP/CM ARE CELL VALUES
OD=INT(15/W(A)) : CP=CP/W(A) : MAZE(P)=CP : CM=CM/OD : MAZE(M)=CM

REM MOVE TO MERGED CELL, INC CONNECTION COUNTER, CONT UNTIL 
REM CONNECTED ALL CELLS (H = TOTAL CELLS - 1)
P=M : C=C+1 : IF C<H THEN GOTO PICKDIR
RETURN

SHOWMAP: 
REM MAP DISPLAY 
? CHR$(147)

REM SCREEN POSITION A=TOP-LEFT OF MAP AREA, MS=SCREEN MEMORY START, 
REM DC/DD=ARRAY INDICES TO READ FROM (MAZE DATA)
A=TL+LL+1 : MS=A : DC=0 : DD=G

MAPROW: 
REM LOOP THROUGH EACH CELL IN CURRENT ROW
FOR B=DC TO DD: X=MAZE(B)

REM IF THIS IS PLAYER, MARK IT
IF B=P THEN POKE A,W4

REM CHECK FOR OPEN IN EACH DIRS AND DRAW  

REM DIR 0 (RIGHT) IF CELL DIVISIBLE BY W(0), DRAW WALLS TO RIGHT
IF X-W(0)*INT(X/W(0))<1 THEN P2=A+1 : POKE P2,W3 : POKE P2+LL,W3 : POKE P2-LL,W3

REM DIR 1 (DOWN) IF CELL DIVISIBLE BY W(1), DRAW WALLS BELOW
IF X-W(1)*INT(X/W(1))<1 THEN P2=A+LL : POKE P2,W3 : POKE P2+1,W3 : POKE P2-1,W3

REM DIR 2 (LEFT) IF CELL DIVISIBLE BY W(2), DRAW WALLS TO LEFT
IF X-W(2)*INT(X/W(2))<1 THEN P2=A-1 : POKE P2,W3 : POKE P2-LL,W3 : POKE P2+LL,W3

REM DIR 3 (UP) IF CELL DIVISIBLE BY W(3), DRAW WALLS ABOVE
IF X-W(3)*INT(X/W(3))<1 THEN P2=A-LL : POKE P2,W3 : POKE P2-1,W3 : POKE P2+1,W3

REM MOVE TO NEXT SCREEN POSITION (2 COLS PER CELL)
A=A+2
NEXT

REM MOVE TO NEXT ROW 
DC=DC+L : DD=DD+L : A=MS+(2*LL) : MS=A

REM CONTINUE UNTIL DISPLAYED ALL ROWS
IF DD<=EM THEN GOTO MAPROW
RETURN

MAZEGEN: 
REM INIT TL=TOP-LEFT, 
REM BL=BOTTOM-LEFT, TR=TOP-RIGHT, BR=B-RIGHT, LL=LINE LENGTH (40 CHARS), 
REM DW=DRAW WIDTH (3), CD=CORRIDOR DEPTH (3)
TL=1144 : BL=1904 : TR=TL+25 : BR=BL+25 : LL=40 : DW=3 : CD=3

REM SET WALL CHARS W1/W2=H-WALLS, W3=V-WALLS, W4=PLAYER
W1=99 : W2=100 : W3=160 : W4=88

REM SET WALL DIVISORS 
REM W(0-3) FOR N/E/S/W, L=RAND MAZE LENGTH (6-10)
W(0)=5 : W(1)=7 : W(2)=3 : W(3)=2 : L=INT(RND(1)*5+6)

REM SET MOVEMENT VECTORS M(0-3) OFFSETS (RIGHT, DOWN, LEFT, UP), 
REM M(4-7) ARE WALL BOUNDARY POSITIONS
M(0)=1 : M(1)=L : M(2)=-1 : M(3)=-L : M(4)=TL : M(5)=BL : M(6)=TR : M(7)=BR

REM CALCULATE 
REM W=WIDTH, H=TOTAL CELLS, G=RIGHT EDGE INDEX, C=CONNECTION COUNTER, 
REM DC=DEPTH, T=TURN, RM=MAP SHOWN FLAG, 
REM SM=START OF MAZE MEMORY (BASE ADDRESS FOR INDEXING), EM=END OF MAZE MEMORY
W=INT(RND(1)*5+6) : H=L*W-1 : G=L-1 : C=0 : DC=0 : T=0 : RM=0 : SM=0 : EM=H 

REM INIT MAZE CELLS TO UNINITD VALUE (210)
FOR A=0 TO H : MAZE(A)=210 : NEXT

REM SET RAND START (P) AND EXIT (EC) 
REM ON TOP ROW, MC=MAP CENTER 
REM P/EC/MC ARE NOW ARRAY INDICES (0 TO H)
P=INT(RND(1)*H) : EC=INT(RND(1)*L) : MC=INT(RND(1)*H)

REM CALCULATE INITIAL OXYGEN BASED ON MAZE SIZE
OX=INT(H/3)+1 : IF P<OX THEN OX=-OX

REM SET FINAL O2 AMOUNT, O2 LOSS PER TURN, 
REM RANDOM TURN THRESHOLD, GEN MAZE CONNECTIONS, 
OX=OX+H : OL=1 : TT=INT(RND(1)*H/8)+1
GOSUB MAZEINIT 
? CHR$(147)

REM SET INITIAL DIR (0=NORTH), MARK EXIT CELL, START GAME
M=0 : NP=P : CE=MAZE(EC) : CE=CE/W(3) : MAZE(EC)=CE
GOTO UPDIRS

FASTMOD:
REM FAST MODULO: MQ=RESULT, QT=TEMP, QV=VALUE, DV=DIVISOR
REM FOR DIV 2 USE BITWISE, OTHERS USE SUBTRACTION
IF DV=2 THEN MQ=QV AND 1 : RETURN
QT=QV
FASTMODLOOP:
IF QT<DV THEN MQ=QT : RETURN
QT=QT-DV : GOTO FASTMODLOOP

WAITKEY: 
REM WAIT FOR KEY PRESS
? " PRESS A KEY "
WAITKEYL: 
A$="" : POKE198,0 : WAIT198,1 : GETA$ : IF A$="" THEN GOTO WAITKEYL
RETURN
